services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672" 
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "server_version"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: on-failure

volumes:
  rabbitmq_data:  # Named volume for persistent RabbitMQ data

networks:
  backend:
    driver: bridge